name: Node.js Package

on:
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Installing SLS Cloud
        run: npm install -g @serverless/cloud

      - name: SLS CLoud Version
        run: cloud -v
        
      - name: Deploying the APIs
        run: cloud activate 466732